# Generated by Django 4.0 on 2022-01-21 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='max',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='mean',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='min',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
